### ISSUE TITLE
Public source code

### ISSUE THREAD

**Issue by def750** [skylandersNFC/wCopy#1]
To help people work with your devices, could you please publish the source code / decumentation how the device works in detail?

**Comment by skylandersNFC** [comment]
This software is developed by a Chinese company. When you purchase a device from them, they typically provide a Google Drive link or another website to download the software. However, they only offer the compiled version, not the source code, which I don't believe is available anywhere.

I've shared the software here to ensure its availability and preservation.

If you have expertise in this area, please feel free to contribute any documentation or findings related to the device or software.

Thank you!
